polygon:
  amoy:
    contractAddress: 0x1a4cC30f2aA0377b0c3bc9848766D90cb4404124
    networkURL: https://polygon-amoy.g.alchemy.com/v2/jDBPucH2EgeZxWFU7shh52EvRVc-HqG_
    chainID: 80002
    networkFlag: 0b0001_0011
    did: did:polygonid:polygon:amoy:2qV9QXdhXXmN5sKjN1YueMjxgRbnJcEGK2kGpvk3cq
    method: polygonid

#  main:
#    contractAddress: 0x624ce98D2d27b20b8f8d521723Df8fC4db71D79D
#    networkURL: https://polygon-mainnet.g.alchemy.com/v2/jDBPucH2EgeZxWFU7shh52EvRVc-HqG_
#    chainID: 137
#    networkFlag: 0b0001_0001
#    did: did:polygonid:polygon:main:2q4Q7F7tM1xpwUTgWivb6TgKX3vWirsE3mqymuYjVv
#    method: polygonid

privado:
  main:
    contractAddress: 0x3C9acB2205Aa72A05F6D77d708b5Cf85FCa3a896
    networkURL: https://rpc-mainnet.privado.id
    chainID: 21000
    networkFlag: 0b0001_0001
    did: did:iden3:polygon:amoy:xCYJvuoMw8QQqQWKogvq5poe82SFy1hGz1iBDz2Wk
    method: iden3
